### ISSUE TITLE
truncate PR body to comply with github api limits

### ISSUE THREAD

**Issue by inverted-capital** [denoland/bump-workspaces#34]
If you make a large number of commits, then the PR body can be generated to exceed 65,536 characters, which will cause the PR to fail.

```js
error: Uncaught (in promise) HttpError: Validation Failed: {"resource":"Issue","code":"custom","field":"body","message":"body is too long (maximum is 65536 characters)"} - https://docs.github.com/rest/pulls/pulls#create-a-pull-request
    at file:///home/runner/.cache/deno/npm/registry.npmjs.org/@octokit/request/8.4.0/dist-node/index.js:125:21
    at eventLoopTick (ext:core/01_core.js:175:7)
    at async requestWithGraphqlErrorHandling (file:///home/runner/.cache/deno/npm/registry.npmjs.org/@octokit/plugin-retry/6.0.1/dist-node/index.js:71:20)
    at async Job.doExecute (file:///home/runner/.cache/deno/npm/registry.npmjs.org/bottleneck/2.19.5/light.js:405:18)
Error: Process completed with exit code 1.
```

**Comment by kt3k** [comment]
I wonder if truncating makes sense here as most part of PR body is important information.

How many commits/packages did your use case have?

**Comment by inverted-capital** [comment]
I'm not sure exactly, but maybe around 1,000 ?

https://github.com/dreamcatcher-tech/napps/actions/runs/11496379758/job/31997878030
